[[courses]]
course_code = "22CS14004E"
course_name = "计算思维与人工智能"
credit = 2.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考查"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 32

[[courses]]
course_code = "22CS21001E"
course_name = "高级语言程序设计"
credit = 4.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 64

[[courses]]
course_code = "22HS16002"
course_name = "初级汉语（1）"
credit = 3.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考查"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22MA15005E"
course_name = "微积分C（1）"
credit = 5.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 80

[[courses]]
course_code = "22MA15017E"
course_name = "代数与几何B"
credit = 3.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 56

[[courses]]
course_code = "22PE13001"
course_name = "体育（1）"
credit = 1.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考查"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[info]
year = "2026"
major_code = "05Y061"
major_name = "电气工程及其自动化"
school_name = "电气工程及自动化学院"
plan_category = "Y"
plan_ID = "HIT-2026-05Y061"
