[[courses]]
course_code = "22CS14004E"
course_name = "计算思维与人工智能"
credit = 2.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考查"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 32

[[courses]]
course_code = "22HS16002"
course_name = "初级汉语（1）"
credit = 3.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS22002E"
course_name = "中国概况"
credit = 2.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考查"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22MA15045E"
course_name = "微积分E（1）"
credit = 4.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 64

[[courses]]
course_code = "22PE13001"
course_name = "体育（1）"
credit = 1.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考查"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[info]
year = "2026"
major_code = "03Y190"
major_name = "材料科学与工程"
school_name = "材料科学与工程学院"
plan_category = "Y"
plan_ID = "HIT-2026-03Y190"
