[[courses]]
course_code = "22CE31028"
course_name = "建筑结构"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 32

[[courses]]
course_code = "22CE31029"
course_name = "经济学基础"
credit = 1.5
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 24

[[courses]]
course_code = "22CE31030"
course_name = "运筹学"
credit = 1.5
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 24

[[courses]]
course_code = "22CE31031"
course_name = "工程经济学A"
credit = 1.5
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 24

[[courses]]
course_code = "22CE33025"
course_name = "工程经济学A课程设计"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "土木工程学院"

[[courses]]
course_code = "22PE13005"
course_name = "体育（5）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[info]
year = "2024"
major_code = "09335"
major_name = "工程管理"
school_name = "土木工程学院"
plan_ID = "HIT-2024-09335"
