[[courses]]
course_code = "22AD11001"
course_name = "思想政治理论实践课"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "思政"
offering_college = "学生工作部（处）/团委"
total_hours = 32

[[courses]]
course_code = "22AD16001"
course_name = "军事理论"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"
total_hours = 36

[[courses]]
course_code = "22AD16004"
course_name = "军事技能"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"

[[courses]]
course_code = "22CS14003"
course_name = "程序设计思维与实践"
credit = 4.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 64

[[courses]]
course_code = "22EI33202"
course_name = "智能感知系统创新实践入门（1）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22FL12003"
course_name = "外语综合（1）"
credit = 2.5
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "英语"
offering_college = "人文社科学部"
total_hours = 60

[[courses]]
course_code = "22MA15015"
course_name = "数学分析（1）"
credit = 5.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 80

[[courses]]
course_code = "22MA15023"
course_name = "代数与几何x"
credit = 4.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 64

[[courses]]
course_code = "22MX11003"
course_name = "中国近现代史纲要"
credit = 2.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22PE13001"
course_name = "体育（1）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[[courses]]
course_code = "22EI31201"
course_name = "电子信息前沿专题讲座"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22AD16003"
course_name = "悦己人生"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"
total_hours = 32

[[courses]]
course_code = "22EI22208"
course_name = "智能感知系统创新实践入门（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI32227"
course_name = "Python科学计算与混合编程实践"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22FL12004"
course_name = "外语综合（2）"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "英语"
offering_college = "人文社科学部"
total_hours = 36

[[courses]]
course_code = "22MA15016"
course_name = "数学分析（2）"
credit = 5.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 80

[[courses]]
course_code = "22MX11001"
course_name = "习近平新时代中国特色社会主义思想概论"
credit = 2.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11002"
course_name = "思想道德与法治"
credit = 2.5
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11006"
course_name = "形势与政策（1）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "22MX16001"
course_name = "国家安全教育"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22PE13002"
course_name = "体育（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[[courses]]
course_code = "22PH15012"
course_name = "大学物理x（1）"
credit = 5.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 80

[[courses]]
course_code = "22PH15014"
course_name = "大学物理实验x（1）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 24

[[courses]]
course_code = "22MX44001"
course_name = "劳动教育概论"
credit = 0.0
assessment_method = "考查"
recommended_year_semester = "第一学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "22EI32255"
course_name = "基于开源Qt的OOP编程与实践"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI22122"
course_name = "电路基础x"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22EI22203"
course_name = "无人感知系统创新设计（1）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22MA15031"
course_name = "概率论与数理统计x"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 48

[[courses]]
course_code = "22MA15032"
course_name = "复变函数与积分变换"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 32

[[courses]]
course_code = "22MX11005"
course_name = "马克思主义基本原理"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22PE13003"
course_name = "体育（3）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22PH15013"
course_name = "大学物理x（2）"
credit = 4.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 64

[[courses]]
course_code = "22PH15015"
course_name = "大学物理实验x（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 24

[[courses]]
course_code = "22EI32101"
course_name = "数学建模方法"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 24

[[courses]]
course_code = "22FL12005"
course_name = "外语综合（3）"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22EI21291"
course_name = "计算机组成原理与嵌入式系统"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22EI21461"
course_name = "电磁场与电磁波A"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22EI21591"
course_name = "信号与系统D"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22EI22204"
course_name = "无人感知系统创新设计（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI22391"
course_name = "模拟与数字电路系统"
credit = 5.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 80

[[courses]]
course_code = "22HS16001"
course_name = "写作与沟通"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22MX11004"
course_name = "毛泽东思想和中国特色社会主义理论体系概论"
credit = 2.5
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11007"
course_name = "形势与政策（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22PE13004"
course_name = "体育（4）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22CS22010"
course_name = "人工智能导论"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 32

[[courses]]
course_code = "22FL12006"
course_name = "外语综合（4）"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22EI32292"
course_name = "复杂嵌入式系统硬件设计实践"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 40

[[courses]]
course_code = "22EI32127"
course_name = "3D视频信号压缩和通信国际前沿技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI32128"
course_name = "数据通信网络"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI32146"
course_name = "计算机网络"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI32231"
course_name = "电子信息类前沿技术讲座——机器学习"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI32232"
course_name = "模式识别与统计机器学习及应用"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI32516"
course_name = "人工智能在专家系统的应用"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI22205"
course_name = "新体制探测与无线系统总体设计（1）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI22294"
course_name = "数字信号处理A"
credit = 3.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22EI22392"
course_name = "射频通信电路"
credit = 3.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22EI31191"
course_name = "现代通信原理A"
credit = 3.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22EI31295"
course_name = "统计信号处理与随机过程"
credit = 3.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22EI31492"
course_name = "微波技术A"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22ME22010"
course_name = "工程训练（制造工艺实习）B"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "机电工程学院"

[[courses]]
course_code = "22PE13005"
course_name = "体育（5）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[info]
year = "2024"
major_code = "5205SY2"
major_name = "永坦班（英才）"
school_name = "未来技术学院"
plan_category = "本"
plan_ID = "HIT-2024-5205SY2"
