[[courses]]
course_code = "22AD11001"
course_name = "思想政治理论实践课"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "思政"
offering_college = "学生工作部（处）/团委"
total_hours = 32

[[courses]]
course_code = "22AD16001"
course_name = "军事理论"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"
total_hours = 36

[[courses]]
course_code = "22AD16004"
course_name = "军事技能"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"

[[courses]]
course_code = "22AS31002"
course_name = "航天工程前沿技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 16

[[courses]]
course_code = "22CS14003"
course_name = "程序设计思维与实践"
credit = 4.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 64

[[courses]]
course_code = "22FL12003"
course_name = "外语综合（1）"
credit = 2.5
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "英语"
offering_college = "人文社科学部"
total_hours = 60

[[courses]]
course_code = "22MA15015"
course_name = "数学分析（1）"
credit = 5.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 80

[[courses]]
course_code = "22MA15023"
course_name = "代数与几何x"
credit = 4.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 64

[[courses]]
course_code = "22MX11003"
course_name = "中国近现代史纲要"
credit = 2.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22PE13001"
course_name = "体育（1）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[[courses]]
course_code = "22AD16003"
course_name = "悦己人生"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"
total_hours = 32

[[courses]]
course_code = "22AS22015"
course_name = "航天器与智能自主系统认知"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22EE21002"
course_name = "电路与电子学"
credit = 4.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电气工程及自动化学院"
total_hours = 64

[[courses]]
course_code = "22EE21003"
course_name = "电路与电子学实验"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "电气工程及自动化学院"
total_hours = 24

[[courses]]
course_code = "22MA15016"
course_name = "数学分析（2）"
credit = 5.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 80

[[courses]]
course_code = "22MX11001"
course_name = "习近平新时代中国特色社会主义思想概论"
credit = 2.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11002"
course_name = "思想道德与法治"
credit = 2.5
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11006"
course_name = "形势与政策（1）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "22MX16001"
course_name = "国家安全教育"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22PE13002"
course_name = "体育（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[[courses]]
course_code = "22PH15012"
course_name = "大学物理x（1）"
credit = 5.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 80

[[courses]]
course_code = "22PH15014"
course_name = "大学物理实验x（1）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 24

[[courses]]
course_code = "22FL12004"
course_name = "外语综合（2）"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "英语"
offering_college = "人文社科学部"
total_hours = 36

[[courses]]
course_code = "22FT32001"
course_name = "未来技术专题"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "未来技术学院"
total_hours = 16

[[courses]]
course_code = "22MX44001"
course_name = "劳动教育概论"
credit = 0.0
assessment_method = "考查"
recommended_year_semester = "第一学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "22AS22003"
course_name = "理论力学B"
credit = 4.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 64

[[courses]]
course_code = "22AS31003"
course_name = "航天器与自主智能系统设计（1）"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22MA15031"
course_name = "概率论与数理统计x"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 48

[[courses]]
course_code = "22MX11005"
course_name = "马克思主义基本原理"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22PE13003"
course_name = "体育（3）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22PH15013"
course_name = "大学物理x（2）"
credit = 4.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 64

[[courses]]
course_code = "22PH15015"
course_name = "大学物理实验x（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 24

[[courses]]
course_code = "22CS22002"
course_name = "数理逻辑与近世代数"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "计算学部"
total_hours = 48

[[courses]]
course_code = "22CS22004"
course_name = "数据结构与算法"
credit = 3.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "计算学部"
total_hours = 56

[[courses]]
course_code = "22MA15033"
course_name = "最优化方法"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "数学学院"
total_hours = 32

[[courses]]
course_code = "22ME21001"
course_name = "设计与制造（1）"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "机电工程学院"
total_hours = 48

[[courses]]
course_code = "22FL12005"
course_name = "外语综合（3）"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22AS31004"
course_name = "航天器与自主智能系统设计（2）"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22AS31051"
course_name = "航天器轨道动力学与控制"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22HS16001"
course_name = "写作与沟通"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22ME22010"
course_name = "工程训练（制造工艺实习）B"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机电工程学院"

[[courses]]
course_code = "22MX11004"
course_name = "毛泽东思想和中国特色社会主义理论体系概论"
credit = 2.5
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11007"
course_name = "形势与政策（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22PE13004"
course_name = "体育（4）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22AS22014"
course_name = "系统与控制"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "限选"
course_category = "其他"
offering_college = "航天学院"
total_hours = 48

[[courses]]
course_code = "22AS31052"
course_name = "变形体力学与有限元"
credit = 4.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "限选"
course_category = "其他"
offering_college = "航天学院"
total_hours = 64

[[courses]]
course_code = "22CS22008"
course_name = "计算机系统"
credit = 3.5
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "限选"
course_category = "其他"
offering_college = "计算学部"
total_hours = 56

[[courses]]
course_code = "22EI22304"
course_name = "信号与系统A"
credit = 3.5
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "限选"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 56

[[courses]]
course_code = "22EI22401"
course_name = "电磁场与电磁波"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "限选"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22ME21002"
course_name = "设计与制造（2）"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "限选"
course_category = "其他"
offering_college = "机电工程学院"
total_hours = 48

[[courses]]
course_code = "22FL12006"
course_name = "外语综合（4）"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22AS32135"
course_name = "新能源功率变换器原理及控制技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "航天学院"
total_hours = 16

[[courses]]
course_code = "22AS32328"
course_name = "超材料基础"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "航天学院"
total_hours = 16

[[courses]]
course_code = "22AS32812"
course_name = "以需求为核心的集成电路芯片设计方法探索"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 16

[[courses]]
course_code = "22AS32814"
course_name = "光电微系统前沿技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 16

[[courses]]
course_code = "22AS44501"
course_name = "空间飞行器有效载荷设计"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "航天学院"
total_hours = 16

[[courses]]
course_code = "22AS31005"
course_name = "航天器与自主智能系统创新设计（1）"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22AS31053"
course_name = "航天器姿态动力学与控制"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22AS31054"
course_name = "航天器总体设计"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22AS31102"
course_name = "自动控制理论（1）"
credit = 5.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 80

[[courses]]
course_code = "22AS31104"
course_name = "自动控制实践（1）"
credit = 4.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 64

[[courses]]
course_code = "22PE13005"
course_name = "体育（5）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22AS31501"
course_name = "弹箭空气动力学"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22AS31601"
course_name = "飞行器结构力学B"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22AS31652"
course_name = "飞行器导航原理"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22AS31653"
course_name = "基础天文学"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22AS32507"
course_name = "航天器敏感元件与执行机构"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 16

[[courses]]
course_code = "22AS32508"
course_name = "航天器电源系统"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 16

[[courses]]
course_code = "22AS32509"
course_name = "微纳卫星星务系统"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 16

[info]
year = "2024"
major_code = "52188"
major_name = "小卫星班(英才)"
school_name = "未来技术学院"
plan_ID = "HIT-2024-52188"
