[[courses]]
course_code = "22MH22020"
course_name = "脑机接口原理"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH31202"
course_name = "医学数据分析与处理"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH31205"
course_name = "智能医学图像处理"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22PE13005"
course_name = "体育（5）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22MH31208"
course_name = "生物传感器基础B"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "限选"
course_category = "其他"
track = "方向2：先进治疗技术"
offering_college = "生命科学和医学学部"
total_hours = 48

[[courses]]
course_code = "22MH31211"
course_name = "互联网医疗与医疗物联网"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "限选"
course_category = "其他"
track = "方向3：智慧医疗与健康"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22CS32702"
course_name = "人工智能数学基础B"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 32

[[courses]]
course_code = "22EE32075"
course_name = "电路与电子技术B"
credit = 4.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电气工程及自动化学院"
total_hours = 64

[[courses]]
course_code = "22EE32076"
course_name = "电路与电子技术实验B"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电气工程及自动化学院"
total_hours = 24

[[courses]]
course_code = "22MH31102"
course_name = "医学遗传学"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH32004"
course_name = "分子影像"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH32047"
course_name = "医学神经生物学"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH32053"
course_name = "公共营养"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 24

[[courses]]
course_code = "22MH32054"
course_name = "毒理学"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH32057"
course_name = "特殊人群营养"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 24

[info]
year = "2024"
major_code = "37521"
major_name = "智能医学工程"
school_name = "生命科学和医学学部"
plan_category = "本"
plan_ID = "HIT-2024-37521"
