[[courses]]
course_code = "22CS22100"
course_name = "数据结构与算法C"
credit = 3.5
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 56

[[courses]]
course_code = "22CS22101"
course_name = "程序设计基础"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 32

[[courses]]
course_code = "22CS22102"
course_name = "Python程序语言设计"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 16

[[courses]]
course_code = "22MA15025"
course_name = "概率论与数理统计C"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 48

[[courses]]
course_code = "22MH22005"
course_name = "新医学科学与技术综合实验（1）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 24

[[courses]]
course_code = "22MH22012"
course_name = "生物化学"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH22013"
course_name = "分子生物学"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH22014"
course_name = "分子生物学综合实验"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 24

[[courses]]
course_code = "22MH22204"
course_name = "生物信息学导论"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MX11004"
course_name = "毛泽东思想和中国特色社会主义理论体系概论"
credit = 2.5
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX16001"
course_name = "国家安全教育"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22MX44001"
course_name = "劳动教育概论"
credit = 0.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "22PE13003"
course_name = "体育（3）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22PH15018"
course_name = "大学物理实验B"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 24

[[courses]]
course_code = "22MH32002"
course_name = "向大自然学习纳米生物技术"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH32022"
course_name = "AI+药食同源与健康"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH32023"
course_name = "微纳机器人原理与医学应用"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22HS16001"
course_name = "写作与沟通"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22MH22004"
course_name = "生物物理"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH22006"
course_name = "新医学科学与技术综合实验（2）"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 48

[[courses]]
course_code = "22MH22007"
course_name = "生物医学统计"
credit = 1.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 16

[[courses]]
course_code = "22MH22023"
course_name = "模式识别与机器学习"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH22024"
course_name = "智能诊断原理及技术"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH31303"
course_name = "系统生物学"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH32202"
course_name = "临床医学概论"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 48

[[courses]]
course_code = "22MX11005"
course_name = "马克思主义基本原理"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22MX11007"
course_name = "形势与政策（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22PE13004"
course_name = "体育（4）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22MH22026"
course_name = "临床医学实验A"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 36

[[courses]]
course_code = "22MH32010"
course_name = "数据挖掘"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH32030"
course_name = "智能仿生医学"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 32

[[courses]]
course_code = "22MH32015"
course_name = "益生菌与肠道健康"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 16

[[courses]]
course_code = "22MH32018"
course_name = "现代模式识别技术与方法"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 16

[[courses]]
course_code = "22MH32020"
course_name = "发育生物学"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 16

[[courses]]
course_code = "22MH32031"
course_name = "基因与疾病"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 24

[[courses]]
course_code = "22MH32032"
course_name = "基因治疗前沿进展"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "生命科学和医学学部"
total_hours = 16

[info]
year = "2024"
major_code = "3721L520"
major_name = "工科试验班（医学类1）"
school_name = "生命科学和医学学部"
plan_category = "本"
plan_ID = "HIT-2024-3721L520"
