[[courses]]
course_code = "22AD11001"
course_name = "思想政治理论实践课"
credit = 2.0
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "思政"
offering_college = "学生工作部（处）/团委"
total_hours = 32

[[courses]]
course_code = "22AD16001"
course_name = "军事理论"
credit = 2.0
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"
total_hours = 36

[[courses]]
course_code = "22AD16004"
course_name = "军事技能"
credit = 2.0
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"

[[courses]]
course_code = "22EM21404"
course_name = "管理学基础"
credit = 3.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业基础"
offering_college = "经济与管理学院"
total_hours = 48

[[courses]]
course_code = "22FL12001"
course_name = "大学外语"
credit = 2.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "英语"
offering_college = "人文社科学部"
total_hours = 60

[[courses]]
course_code = "22HS16001"
course_name = "写作与沟通"
credit = 1.0
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22MA15009"
course_name = "微积分E（1）"
credit = 4.0
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 64

[[courses]]
course_code = "22MA15022"
course_name = "代数与几何H"
credit = 3.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 48

[[courses]]
course_code = "22MX11001"
course_name = "习近平新时代中国特色社会主义思想概论"
credit = 2.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11003"
course_name = "中国近现代史纲要"
credit = 2.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX16001"
course_name = "国家安全教育"
credit = 1.0
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22PE13001"
course_name = "体育（1）"
credit = 1.0
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[[courses]]
course_code = "22AD16003"
course_name = "悦己人生"
credit = 2.0
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"
total_hours = 32

[[courses]]
course_code = "22CS14004"
course_name = "计算思维与人工智能"
credit = 2.0
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 32

[[courses]]
course_code = "22EM21901"
course_name = "经济学原理"
credit = 4.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业基础"
offering_college = "经济与管理学院"
total_hours = 64

[[courses]]
course_code = "22FL12002"
course_name = "大学外语"
credit = 1.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "英语"
offering_college = "人文社科学部"
total_hours = 36

[[courses]]
course_code = "22HS22103"
course_name = "社会学概论"
credit = 3.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业基础"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS22301"
course_name = "习近平法治思想概论"
credit = 1.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业基础"
offering_college = "人文社科学部"
total_hours = 24

[[courses]]
course_code = "22MA15010"
course_name = "微积分E（2）"
credit = 4.0
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 64

[[courses]]
course_code = "22MX11002"
course_name = "思想道德与法治"
credit = 2.5
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11006"
course_name = "形势与政策（1）"
credit = 0.5
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "22PE13002"
course_name = "体育（2）"
credit = 1.0
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[info]
year = "2024"
major_code = "10L0124L1001"
major_name = "经济管理试验班"
school_name = "经济管理试验班"
plan_ID = "HIT-2024-10L0124L1001"
