[[courses]]
course_code = "22AS31802"
course_name = "微电子工艺"
credit = 2.5
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 40

[[courses]]
course_code = "22AS31807"
course_name = "微电子系列实验"
credit = 1.0
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 24

[[courses]]
course_code = "22AS31854"
course_name = "半导体器件物理"
credit = 3.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 48

[[courses]]
course_code = "22AS33803"
course_name = "认识实习"
credit = 1.0
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"

[[courses]]
course_code = "22AS33805"
course_name = "生产实习"
credit = 2.0
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"

[[courses]]
course_code = "22EI22202"
course_name = "数字信号处理"
credit = 3.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22PE13005"
course_name = "体育（5）"
credit = 0.5
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[info]
year = "2024"
major_code = "01215"
major_name = "集成电路设计与集成系统"
school_name = "航天学院"
plan_ID = "HIT-2024-01215"
