[[courses]]
course_code = "22CC22021"
course_name = "化学基础实验D"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "专业基础"
offering_college = "化工与化学学院"
total_hours = 72

[[courses]]
course_code = "22CC22022"
course_name = "大型仪器分析实验"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "专业基础"
offering_college = "化工与化学学院"
total_hours = 48

[[courses]]
course_code = "22CC22027"
course_name = "计算化学B"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 32

[[courses]]
course_code = "22CC31028"
course_name = "电化学原理A"
credit = 5.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "化工与化学学院"
total_hours = 80

[[courses]]
course_code = "22ME21005"
course_name = "工程制图基础B"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "机电工程学院"
total_hours = 32

[[courses]]
course_code = "22PE13005"
course_name = "体育（5）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22CC32001"
course_name = "英文科技写作"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32037"
course_name = "化工过程分析与合成"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 32

[[courses]]
course_code = "22CC32038"
course_name = "化工分离工程"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 32

[[courses]]
course_code = "22CC32039"
course_name = "化工设备机械基础"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 32

[[courses]]
course_code = "22CC32040"
course_name = "化学反应工程"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 32

[[courses]]
course_code = "22CC32041"
course_name = "化工设计基础"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 32

[[courses]]
course_code = "22CC32042"
course_name = "化工热力学"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 32

[[courses]]
course_code = "22CC32086"
course_name = "AI+电化学"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 24

[[courses]]
course_code = "22CC31029"
course_name = "电化学测量A"
credit = 3.0
recommended_year_semester = "第三学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "化工与化学学院"
total_hours = 48

[[courses]]
course_code = "22CC31030"
course_name = "电镀基础理论"
credit = 2.0
recommended_year_semester = "第三学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "化工与化学学院"
total_hours = 32

[[courses]]
course_code = "22CC31031"
course_name = "化学电源基础理论"
credit = 2.0
recommended_year_semester = "第三学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "化工与化学学院"
total_hours = 32

[[courses]]
course_code = "22CC31032"
course_name = "电化学综合实验"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "必修"
course_category = "专业核心"
offering_college = "化工与化学学院"
total_hours = 48

[[courses]]
course_code = "22MX11008"
course_name = "形势与政策（3）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "22PE13006"
course_name = "体育（6）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22CC32029"
course_name = "电极材料结构分析"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32030"
course_name = "电催化原理"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32031"
course_name = "金属腐蚀原理"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32033"
course_name = "先进电镀技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32034"
course_name = "先进化学电源技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32035"
course_name = "化工企业技术创新与应用"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32043"
course_name = "电动车能源系统"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32044"
course_name = "电化学反应工程"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32045"
course_name = "电化学加工技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32046"
course_name = "无机材料合成方法"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32047"
course_name = "固体电化学基础"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32048"
course_name = "纳米电化学技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32049"
course_name = "汽车涂装技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32050"
course_name = "新型化学电源"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32051"
course_name = "仿生功能性电极材料"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32052"
course_name = "先进电化学储能材料"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32053"
course_name = "电池反应与可视化技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC31033"
course_name = "电化学工程实验"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第四学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 48

[[courses]]
course_code = "22CC32036"
course_name = "电化学工程设计"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第四学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"

[[courses]]
course_code = "22CC32078"
course_name = "电化学创新设计"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第四学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"

[[courses]]
course_code = "22CC32083"
course_name = "专业思维训练"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第四学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 16

[[courses]]
course_code = "22CC32086"
course_name = "AI+电化学"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第四学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "化工与化学学院"
total_hours = 24

[info]
year = "2024"
major_code = "25142"
major_name = "化学工程与工艺"
school_name = "化工与化学学院"
plan_ID = "HIT-2024-25142"
