[[courses]]
course_code = "22ME22011"
course_name = "工程训练（电子工艺实习）"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "机电工程学院"

[[courses]]
course_code = "22MS22106"
course_name = "材料分析测试方法"
credit = 3.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 48

[[courses]]
course_code = "22MS31603"
course_name = "半导体器件物理A"
credit = 2.5
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 40

[[courses]]
course_code = "22MS31606B"
course_name = "微电子制造技术"
credit = 2.5
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 40

[[courses]]
course_code = "22PE13005"
course_name = "体育（5）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22MS32159"
course_name = "金属微观结构发展的基础及纳米结构控制的可能性"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[[courses]]
course_code = "22MS32601"
course_name = "先进印刷电路板材料与制造"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[[courses]]
course_code = "22MS32602B"
course_name = "集成电路热管理技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[[courses]]
course_code = "22MS32603"
course_name = "混合微电路技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[[courses]]
course_code = "22MS32604"
course_name = "纳米电化学"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[[courses]]
course_code = "22MS32605"
course_name = "电子封装模拟与仿真"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 24

[[courses]]
course_code = "22MS32606"
course_name = "电子制造装备"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[[courses]]
course_code = "22MS32607"
course_name = "电子封装新兴技术简介"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[[courses]]
course_code = "22MS32608"
course_name = "光烧结与柔性印刷电子"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[[courses]]
course_code = "22MS32609"
course_name = "电子封装国际标准认证"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[[courses]]
course_code = "22MS32610"
course_name = "化学微加工"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[[courses]]
course_code = "22MS32611"
course_name = "纳米材料与连接"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "材料科学与工程学院"
total_hours = 16

[info]
year = "2024"
major_code = "03292"
major_name = "电子封装技术"
school_name = "材料科学与工程学院"
plan_ID = "HIT-2024-03292"
