[[courses]]
course_code = "22AD11001"
course_name = "思想政治理论实践课"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "思政"
offering_college = "学生工作部（处）/团委"
total_hours = 32

[[courses]]
course_code = "22AD16001"
course_name = "军事理论"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"
total_hours = 36

[[courses]]
course_code = "22AD16004"
course_name = "军事技能"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"

[[courses]]
course_code = "22EM21404"
course_name = "管理学基础"
credit = 3.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 48

[[courses]]
course_code = "22FL12001"
course_name = "大学外语"
credit = 2.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "英语"
offering_college = "人文社科学部"
total_hours = 60

[[courses]]
course_code = "22HS16001"
course_name = "写作与沟通"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22MA15009"
course_name = "微积分E（1）"
credit = 4.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 64

[[courses]]
course_code = "22MA15022"
course_name = "代数与几何H"
credit = 3.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 48

[[courses]]
course_code = "22MX11001"
course_name = "习近平新时代中国特色社会主义思想概论"
credit = 2.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11003"
course_name = "中国近现代史纲要"
credit = 2.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX16001"
course_name = "国家安全教育"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22PE13001"
course_name = "体育（1）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[[courses]]
course_code = "22AD16003"
course_name = "悦己人生"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "学生工作部（处）/团委"
total_hours = 32

[[courses]]
course_code = "22CS14004"
course_name = "计算思维与人工智能"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 32

[[courses]]
course_code = "22EM21901"
course_name = "经济学原理"
credit = 4.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 64

[[courses]]
course_code = "22FL12002"
course_name = "大学外语"
credit = 1.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "英语"
offering_college = "人文社科学部"
total_hours = 36

[[courses]]
course_code = "22HS22103"
course_name = "社会学概论"
credit = 3.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS22301"
course_name = "习近平法治思想概论"
credit = 1.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 24

[[courses]]
course_code = "22MA15010"
course_name = "微积分E（2）"
credit = 4.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 64

[[courses]]
course_code = "22MX11002"
course_name = "思想道德与法治"
credit = 2.5
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11006"
course_name = "形势与政策（1）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "22PE13002"
course_name = "体育（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[[courses]]
course_code = "22MX21005"
course_name = "马克思主义政治经济学"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22MX22001"
course_name = "政治学概论"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22MX22002"
course_name = "马克思主义哲学"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22MX22008"
course_name = "中共党史"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22MX31002"
course_name = "思想政治教育学原理"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22MX31011"
course_name = "马克思主义经典著作导读（1）"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22PE13003"
course_name = "体育（3）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22MX32008"
course_name = "中国哲学史"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22MX11007"
course_name = "形势与政策（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22MX21002"
course_name = "科学社会主义"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22MX22007"
course_name = "马克思主义发展史"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22MX22025"
course_name = "毛泽东思想"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22MX31012"
course_name = "马克思主义经典著作导读（2）"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 24

[[courses]]
course_code = "22MX32009"
course_name = "中国共产党建设的理论与实践"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22PE13004"
course_name = "体育（4）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22MX32005"
course_name = "中国公务员制度概论"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 24

[[courses]]
course_code = "22MX44001"
course_name = "劳动教育概论"
credit = 0.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "22EM22007"
course_name = "人工智能与机器学习"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 24

[[courses]]
course_code = "22MX11008"
course_name = "形势与政策（3）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "22MX22004"
course_name = "政治思想史概论"
credit = 3.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22MX22012"
course_name = "马克思主义理论专业英语"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22MX22027"
course_name = "中国特色社会主义理论"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22MX31013"
course_name = "中华人民共和国国史"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22MX31014"
course_name = "中国化马克思主义重要文献选读（1）"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[[courses]]
course_code = "22PE13005"
course_name = "体育（5）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22MX31009"
course_name = "企业文化与企业思想政治工作"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 32

[info]
year = "2024"
major_code = "49492"
major_name = "马克思主义理论"
school_name = "马克思主义学院"
plan_ID = "HIT-2024-49492"
