[[courses]]
course_code = "22CE31001"
course_name = "结构动力学"
credit = 1.5
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 24

[[courses]]
course_code = "22CE31003"
course_name = "钢结构基本原理"
credit = 3.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 48

[[courses]]
course_code = "22CE31035"
course_name = "混凝土结构原理"
credit = 3.5
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 56

[[courses]]
course_code = "22CE31036"
course_name = "机器学习"
credit = 1.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 16

[[courses]]
course_code = "22CE31037"
course_name = "深度学习"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 32

[[courses]]
course_code = "22PE13005"
course_name = "体育（5）"
credit = 0.5
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22CE32067"
course_name = "量子力学"
credit = 2.0
recommended_year_semester = "第三学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 32

[[courses]]
course_code = "22CE32068"
course_name = "弹性力学A"
credit = 2.0
recommended_year_semester = "第三学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 32

[[courses]]
course_code = "22MA22012"
course_name = "概率论"
credit = 4.5
recommended_year_semester = "第三学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "数学学院"
total_hours = 72

[[courses]]
course_code = "22CE32094"
course_name = "机器视觉智能监测"
credit = 2.0
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "土木工程学院"
total_hours = 32

[info]
year = "2024"
major_code = "09336"
major_name = "智能建造"
school_name = "土木工程学院"
plan_ID = "HIT-2024-09336"
