[[courses]]
course_code = "22AR21002"
course_name = "专业认知实践"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"

[[courses]]
course_code = "22AR31202"
course_name = "流体力学"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 48

[[courses]]
course_code = "22AS22004"
course_name = "理论力学C"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[[courses]]
course_code = "22HS16001"
course_name = "写作与沟通"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22MA15027"
course_name = "概率论与数理统计E"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 48

[[courses]]
course_code = "22MX11005"
course_name = "马克思主义基本原理"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22MX16001"
course_name = "国家安全教育"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22PE13003"
course_name = "体育（3）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22PH15018"
course_name = "大学物理实验B"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 24

[[courses]]
course_code = "22AR31201"
course_name = "工程热力学"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 48

[[courses]]
course_code = "22AR31203"
course_name = "传热学"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 48

[[courses]]
course_code = "22AR31205"
course_name = "流体输配管网"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 32

[[courses]]
course_code = "22EE22013"
course_name = "电工与电子技术D"
credit = 2.5
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电气工程及自动化学院"
total_hours = 40

[[courses]]
course_code = "22ME22010"
course_name = "工程训练（制造工艺实习）B"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "机电工程学院"

[[courses]]
course_code = "22MX11004"
course_name = "毛泽东思想和中国特色社会主义理论体系概论"
credit = 2.5
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 40

[[courses]]
course_code = "22MX11007"
course_name = "形势与政策（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22PE13004"
course_name = "体育（4）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22AR33206"
course_name = "程序设计实习"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"

[[courses]]
course_code = "22MX44001"
course_name = "劳动教育概论"
credit = 0.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 8

[[courses]]
course_code = "13SE93400300"
course_name = "景观学研究方法"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "22AR32006"
course_name = "生成式计算艺术与跨媒介设计实践"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "22AR32007"
course_name = "碳中和城市前沿"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "AR33004"
course_name = "基于城市可持续更新的住区设计体系"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "AR33007"
course_name = "未原型设计：建筑和城市形态创新研究"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "建筑与设计学院"
total_hours = 24

[[courses]]
course_code = "AR33014"
course_name = "智慧城市能源计量过程架构与实现"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年夏季"
course_nature = "选修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "22AR22201"
course_name = "建筑环境学"
credit = 2.5
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 40

[[courses]]
course_code = "22AR31204"
course_name = "热质交换原理与设备"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 32

[[courses]]
course_code = "22AR33209"
course_name = "课程设计-1"
credit = 4.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"

[[courses]]
course_code = "22EE22032"
course_name = "电工与电子技术实验D"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "电气工程及自动化学院"
total_hours = 24

[[courses]]
course_code = "22ME22004"
course_name = "机械设计基础C"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "机电工程学院"
total_hours = 32

[[courses]]
course_code = "22PE13005"
course_name = "体育（5）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22AR31208"
course_name = "建筑冷热源"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 48

[[courses]]
course_code = "22AR31209"
course_name = "供热工程"
credit = 2.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 40

[[courses]]
course_code = "22AR31214"
course_name = "供热工程基础"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 24

[[courses]]
course_code = "22AR31215"
course_name = "燃气输配与储存"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 48

[[courses]]
course_code = "22AR32206"
course_name = "化工原理"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "22AR32004"
course_name = "太阳能能源工程"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "海外课程"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "22AR32204"
course_name = "新能源概论"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "22AR32205"
course_name = "低碳能源技术与应用"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 32

[[courses]]
course_code = "22AR32213"
course_name = "绿色建筑"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "22AR32214"
course_name = "建筑传热（双语）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "22AR32215"
course_name = "数据挖掘与能源智慧管理"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第三学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 32

[info]
year = "2024"
major_code = "11B262"
major_name = "建筑环境与能源应用工程"
school_name = "建筑与设计学院"
plan_ID = "HIT-2024-11B262"
