[[courses]]
course_code = "22CS21004"
course_name = "离散数学"
credit = 4.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 64

[[courses]]
course_code = "22EE22048"
course_name = "电路与电子技术实验A"
credit = 2.0
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "电气工程及自动化学院"
total_hours = 48

[[courses]]
course_code = "22EE32078"
course_name = "电路与电子技术（2）"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电气工程及自动化学院"
total_hours = 32

[[courses]]
course_code = "22MA15031"
course_name = "概率论与数理统计x"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 48

[[courses]]
course_code = "22MA15032"
course_name = "复变函数与积分变换"
credit = 2.0
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 32

[[courses]]
course_code = "22MX11005"
course_name = "马克思主义基本原理"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22MX16001"
course_name = "国家安全教育"
credit = 1.0
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "马克思主义学院"
total_hours = 16

[[courses]]
course_code = "22PE13003"
course_name = "体育（3）"
credit = 0.5
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22PH15013"
course_name = "大学物理x（2）"
credit = 4.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 64

[[courses]]
course_code = "22PH15014"
course_name = "大学物理实验x（1）"
credit = 1.0
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 24

[info]
year = "2025"
major_code = "2025AI"
major_name = "AI加先进技术领军班"
school_name = "电子与信息工程学院"
plan_ID = "HIT-2025-2025AI"
