[[courses]]
course_code = "22AS22001"
course_name = "理论力学"
credit = 4.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 64

[[courses]]
course_code = "22MA15031"
course_name = "概率论与数理统计x"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 48

[[courses]]
course_code = "22ME21001"
course_name = "设计与制造（1）"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "机电工程学院"
total_hours = 48

[[courses]]
course_code = "22MX11005"
course_name = "马克思主义基本原理"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "思政"
offering_college = "马克思主义学院"
total_hours = 48

[[courses]]
course_code = "22PE13003"
course_name = "体育（3）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22PH15013"
course_name = "大学物理x（2）"
credit = 4.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 64

[[courses]]
course_code = "22PH15015"
course_name = "大学物理实验x（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 24

[[courses]]
course_code = "22EM32413"
course_name = "领导力与沟通"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 16

[[courses]]
course_code = "22EN22012"
course_name = "工程伦理学"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "限选"
course_category = "其他"
offering_college = "环境学院"
total_hours = 16

[[courses]]
course_code = "22ES22003"
course_name = "热力学基础"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "能源科学与工程学院"
total_hours = 32

[[courses]]
course_code = "22FL12005"
course_name = "外语综合（3）"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[info]
year = "2025"
major_code = "52WL03"
major_name = "智能制造领域方向（2+X模式）"
school_name = "未来技术学院"
plan_ID = "HIT-2025-52WL03"
