[[courses]]
course_code = "22EI22102"
course_name = "电路基础A"
credit = 2.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 40

[[courses]]
course_code = "22EI22201"
course_name = "微机与微控制器原理"
credit = 2.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI22302"
course_name = "信息论"
credit = 1.5
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 24

[[courses]]
course_code = "22EI22401"
course_name = "电磁场与电磁波"
credit = 3.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22MA15035"
course_name = "复变函数与积分变换A"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 48

[[courses]]
course_code = "22EI22303"
course_name = "电子线路基础"
credit = 2.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 40

[[courses]]
course_code = "22EI22304"
course_name = "信号与系统A"
credit = 3.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 56

[[courses]]
course_code = "22EI22306"
course_name = "数字逻辑电路与系统"
credit = 2.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 40

[[courses]]
course_code = "22EI31207"
course_name = "智能信号处理导论"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI33309"
course_name = "电子系统综合设计"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"

[[courses]]
course_code = "22EI32211"
course_name = "电子对抗技术B"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI32212"
course_name = "软件无线电技术"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI32215"
course_name = "大数据处理与信息融合"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI32127"
course_name = "3D视频信号压缩和通信国际前沿技术"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年夏季"
course_nature = "限选"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI32128"
course_name = "数据通信网络"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年夏季"
course_nature = "限选"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI32129"
course_name = "物联网基础与前沿研究"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年夏季"
course_nature = "限选"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI32232"
course_name = "模式识别与统计机器学习及应用"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年夏季"
course_nature = "限选"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI32516"
course_name = "人工智能在专家系统的应用"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年夏季"
course_nature = "限选"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 16

[[courses]]
course_code = "22EI22202"
course_name = "数字信号处理"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 48

[[courses]]
course_code = "22EI22308"
course_name = "通信电子线路B"
credit = 2.5
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 40

[[courses]]
course_code = "22EI31104"
course_name = "通信原理B"
credit = 2.5
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 40

[[courses]]
course_code = "22EI31203"
course_name = "随机信号分析A"
credit = 2.5
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 40

[[courses]]
course_code = "22EI32124"
course_name = "基于FPGA的创新实践"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 24

[[courses]]
course_code = "22EI32125"
course_name = "基于ARM的嵌入式系统设计与应用"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 24

[[courses]]
course_code = "22EI32214"
course_name = "雷达系统建模与仿真基础"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI32216"
course_name = "FPGA数字系统设计"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI32217"
course_name = "优化算法基础与应用"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI32218"
course_name = "压缩感知技术导论"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI32219"
course_name = "实时操作系统"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI32336"
course_name = "电子系统硬件设计与实践"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 24

[[courses]]
course_code = "22EI32413"
course_name = "基于单片机的创新实践"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 24

[[courses]]
course_code = "22EI33223"
course_name = "生产实习"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "电子与信息工程学院"

[[courses]]
course_code = "22EI31205"
course_name = "无线电定位原理与技术A"
credit = 2.5
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 40

[[courses]]
course_code = "22EI31317"
course_name = "数字图像处理基础"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI31403"
course_name = "微波技术"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI31404"
course_name = "天线原理"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"
total_hours = 32

[[courses]]
course_code = "22EI33224"
course_name = "毕业论文(设计）"
credit = 8.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "电子与信息工程学院"

[info]
year = "2024"
major_code = "20E052"
major_name = "电子信息工程"
school_name = "电子与信息工程学院"
plan_ID = "HIT-2024-20E052"
