[[courses]]
course_code = "22HS22390"
course_name = "法理学A"
credit = 3.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业基础"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS22391"
course_name = "宪法学A"
credit = 3.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业基础"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS22392"
course_name = "民法总论"
credit = 3.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业基础"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS31391"
course_name = "中国法律史"
credit = 1.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "人文社科学部"
total_hours = 24

[[courses]]
course_code = "22HS32112"
course_name = "社会保障学"
credit = 1.0
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS32332"
course_name = "宏观经济学B"
credit = 1.0
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS32333"
course_name = "西方法律思想史B"
credit = 2.0
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32334"
course_name = "管理学"
credit = 1.0
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS32336"
course_name = "习近平国际经济法治思想"
credit = 2.0
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32337"
course_name = "网络法前沿"
credit = 2.0
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32338"
course_name = "法律社会学"
credit = 1.0
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS32340"
course_name = "法律英语"
credit = 1.0
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS32343"
course_name = "文献检索与应用"
credit = 1.0
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS32344"
course_name = "应急管理"
credit = 1.0
recommended_year_semester = "第一学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS22301"
course_name = "习近平法治思想概论"
credit = 1.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "人文社科学部"
total_hours = 24

[[courses]]
course_code = "22HS22358"
course_name = "国际法"
credit = 3.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS31392"
course_name = "法律职业伦理A"
credit = 1.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "人文社科学部"
total_hours = 24

[[courses]]
course_code = "22HS31393"
course_name = "刑法总论B"
credit = 3.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS32320"
course_name = "知识产权法B"
credit = 2.0
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32321"
course_name = "物权法B"
credit = 2.0
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32322"
course_name = "合同法B"
credit = 2.0
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32323"
course_name = "侵权责任法B"
credit = 2.0
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32324"
course_name = "婚姻家庭与继承法"
credit = 2.0
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32335"
course_name = "人工智能法学概论"
credit = 1.0
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS32339"
course_name = "法律经济学"
credit = 1.0
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS32342"
course_name = "计算机软件保护"
credit = 1.0
recommended_year_semester = "第一学年春季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS22359"
course_name = "民事诉讼法"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS22360"
course_name = "刑事诉讼法"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS22361"
course_name = "行政法与行政诉讼法"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业核心"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS31307"
course_name = "证据学"
credit = 1.0
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS32218"
course_name = "WTO规则与应用"
credit = 1.0
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 16

[[courses]]
course_code = "22HS32325"
course_name = "商法B"
credit = 2.0
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32326"
course_name = "经济法A"
credit = 2.0
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32327"
course_name = "劳动与社会保障法B"
credit = 2.0
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32328"
course_name = "国际私法B"
credit = 2.0
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32329"
course_name = "国际经济法B"
credit = 2.0
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32346"
course_name = "法律文书写作实训"
credit = 2.0
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22HS32347"
course_name = "模拟法庭与法律实务"
credit = 2.0
recommended_year_semester = "第二学年秋季"
course_nature = "选修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[info]
year = "2025"
major_code = "35E242"
major_name = "法学"
school_name = "人文社科学部"
plan_ID = "HIT-2025-35E242"
