[[courses]]
course_code = "22AR22601F"
course_name = "设计美学"
credit = 1.5
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 24

[[courses]]
course_code = "22AR22901F"
course_name = "用户体验方法与度量"
credit = 1.5
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 24

[[courses]]
course_code = "22AR22501F"
course_name = "设计史"
credit = 1.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "22AR31601F"
course_name = "数字剪辑与合成"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 32

[[courses]]
course_code = "22AR31602F"
course_name = "录音艺术与声音设计"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 32

[[courses]]
course_code = "22AR22502F"
course_name = "公共艺术设计"
credit = 1.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "跨专业发展"
offering_college = "建筑与设计学院"
total_hours = 16

[[courses]]
course_code = "22AR22602F"
course_name = "传播学"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "跨专业发展"
offering_college = "建筑与设计学院"
total_hours = 32

[[courses]]
course_code = "22AR31603F"
course_name = "交互设计"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "跨专业发展"
offering_college = "建筑与设计学院"
total_hours = 32

[[courses]]
course_code = "22AR31604F"
course_name = "电子游戏设计与制作"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "跨专业发展"
offering_college = "建筑与设计学院"
total_hours = 32

[info]
year = "2024"
major_code = "11BF304"
major_name = "数字媒体艺术"
school_name = "建筑与设计学院"
plan_ID = "HIT-2024-11BF304"
