[[courses]]
course_code = "22AS22251F"
course_name = "理论力学E"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "航天学院"
total_hours = 32

[info]
year = "2025"
major_code = "01F181"
major_name = "工程力学"
school_name = "航天学院"
plan_category = "辅修"
plan_ID = "HIT-2025-01F181"
