[[courses]]
course_code = "22AR22601F"
course_name = "设计美学"
credit = 1.5
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 24

[[courses]]
course_code = "22AR22901F"
course_name = "用户体验方法与度量"
credit = 1.5
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "建筑与设计学院"
total_hours = 24

[info]
year = "2025"
major_code = "11BF304"
major_name = "数字媒体艺术"
school_name = "建筑与设计学院"
plan_ID = "HIT-2025-11BF304"
