[[courses]]
course_code = "22EM21401F"
course_name = "管理学基础"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 32

[[courses]]
course_code = "22EM31402F"
course_name = "组织行为学"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 32

[info]
year = "2025"
major_code = "60F201"
major_name = "工商管理"
school_name = "商学院"
plan_ID = "HIT-2025-60F201"
