[[courses]]
course_code = "22CS14004E"
course_name = "计算思维与人工智能"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 32

[[courses]]
course_code = "22CS21001E"
course_name = "高级语言程序设计"
credit = 4.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 64

[[courses]]
course_code = "22HS16002"
course_name = "初级汉语（1）"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22HS22002E"
course_name = "中国概况"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22MA15005E"
course_name = "微积分C（1）"
credit = 5.0
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 80

[[courses]]
course_code = "22MA15017E"
course_name = "代数与几何B"
credit = 3.5
recommended_year_semester = "第一学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 56

[[courses]]
course_code = "22PE13001"
course_name = "体育（1）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[[courses]]
course_code = "22CS21007E"
course_name = "计算与智能程序设计"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 48

[[courses]]
course_code = "22HS16003"
course_name = "初级汉语（2）"
credit = 3.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 48

[[courses]]
course_code = "22MA15006E"
course_name = "微积分C（2）"
credit = 5.0
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 80

[[courses]]
course_code = "22PE13002"
course_name = "体育（2）"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第一学年春季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 32

[[courses]]
course_code = "22PH15001E"
course_name = "大学物理B（1）"
credit = 4.5
recommended_year_semester = "第一学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 72

[[courses]]
course_code = "22CS21004E"
course_name = "离散数学"
credit = 4.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 64

[[courses]]
course_code = "22EE32077E"
course_name = "电路与电子技术（1）"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "电气工程及自动化学院"
total_hours = 48

[[courses]]
course_code = "22HS16004"
course_name = "中级汉语（1）"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22MA15050E"
course_name = "概率论与数理统计F"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "数学学院"
total_hours = 48

[[courses]]
course_code = "22PE13003"
course_name = "体育（3）"
credit = 0.5
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "体育"
offering_college = "体育部"
total_hours = 16

[[courses]]
course_code = "22PH15002E"
course_name = "大学物理B（2）"
credit = 4.5
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 72

[[courses]]
course_code = "22PH15018E"
course_name = "大学物理实验B"
credit = 1.0
assessment_method = "考查"
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "物理学院"
total_hours = 24

[info]
year = "2025"
major_code = "13BY031"
major_name = "计算机科学与技术"
school_name = "计算学部"
plan_ID = "HIT-2025-13BY031"
