[[courses]]
course_code = "22FL22601F"
course_name = "国际组织谈判实训"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业基础"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22FL22602F"
course_name = "中西文化对比"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业基础"
offering_college = "人文社科学部"
total_hours = 32

[[courses]]
course_code = "22FL22603F"
course_name = "法语"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "专业基础"
offering_college = "人文社科学部"
total_hours = 48

[info]
year = "2025"
major_code = "35F154"
major_name = "国际组织与全球治理"
school_name = "人文社科学部"
plan_category = "辅修"
plan_ID = "HIT-2025-35F154"
