[[courses]]
course_code = "22EM22001F"
course_name = "公共事务治理与领导力"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 32

[[courses]]
course_code = "22EM22002F"
course_name = "当代政治学与公共政策"
credit = 2.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 32

[[courses]]
course_code = "22EM31101F"
course_name = "大数据与社会治理"
credit = 2.0
recommended_year_semester = "第二学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 32

[[courses]]
course_code = "22EM22003F"
course_name = "公共工程经济学"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 32

[[courses]]
course_code = "22EM31202F"
course_name = "人力资源管理"
credit = 2.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 32

[[courses]]
course_code = "22EM31104F"
course_name = "地方政府治理与城市发展"
credit = 2.0
recommended_year_semester = "第三学年秋季"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 32

[[courses]]
course_code = "22EM31203F"
course_name = "区域经济学"
credit = 2.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "经济与管理学院"
total_hours = 32

[info]
year = "2024"
major_code = "07F206S"
major_name = "公共行政领导力"
school_name = "经济与管理学院"
plan_ID = "HIT-2024-07F206S"
