[[courses]]
course_code = "22CS22004F"
course_name = "数据结构与算法"
credit = 3.0
recommended_year_semester = "第二学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 48

[[courses]]
course_code = "22CS22010F"
course_name = "人工智能导论"
credit = 2.0
assessment_method = "考查"
recommended_year_semester = "第二学年春季"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 32

[[courses]]
course_code = "22CS31080F"
course_name = "人工智能数学基础"
credit = 3.0
recommended_year_semester = "第二学年春季"
assessment_method = "考试"
course_nature = "必修"
course_category = "其他"
offering_college = "计算学部"
total_hours = 48

[[courses]]
course_code = "22CS31081F"
course_name = "模式识别与机器学习"
credit = 3.0
recommended_year_semester = "第三学年秋季"
assessment_method = "考试"
course_nature = "必修"
course_category = "跨专业发展"
offering_college = "计算学部"
total_hours = 48

[info]
year = "2024"
major_code = "13BF036"
major_name = "人工智能"
school_name = "计算学部"
plan_ID = "HIT-2024-13BF036"
